spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${url}:3306/joylog_blog?characterEncoding=utf8
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80
