spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80
